
export type EntityId = string;

export enum PropertyType {
  APARTMENT = 'Apartment',
  HOUSE = 'House',
  COMMERCIAL = 'Commercial',
  PARKING = 'Parking',
  OTHER = 'Other',
}

export interface MortgageConfig {
  loanAmount: number;
  startDate: string; // ISO Date
  interestRate: number; // Annual %
  principalRate: number; // Annual % (Initial Tilgung)
  bankName?: string;
  paymentTiming: 'START_OF_MONTH' | 'END_OF_MONTH';
}

export interface Property {
  id: EntityId;
  name: string;
  address: string;
  type: PropertyType;
  notes?: string;
  mortgage?: MortgageConfig;
}

export interface Tenant {
  id: EntityId;
  name: string;
  propertyId: EntityId;
  startDate: string; // ISO Date
  endDate?: string; // ISO Date
  isCurrent: boolean;
  notes?: string;
}

export enum CounterpartyType {
  TENANT = 'Tenant',
  PROVIDER = 'Utility Provider',
  BANK = 'Bank',
  TAX_OFFICE = 'Tax Office',
  TRADESMAN = 'Tradesman',
  OTHER = 'Other',
}

export interface Counterparty {
  id: EntityId;
  name: string;
  type: CounterpartyType;
  email?: string;
  phone?: string;
  notes?: string;
}

export enum CategoryType {
  INCOME = 'Income',
  EXPENSE = 'Expense',
}

export interface Category {
  id: EntityId;
  name: string;
  type: CategoryType;
  isTaxRelevant: boolean;
}

export enum DocumentType {
  INVOICE = 'Invoice',
  RECEIPT = 'Receipt',
  CONTRACT = 'Contract',
  UTILITY_BILL = 'Utility Bill',
  TAX_STATEMENT = 'Tax Statement',
  OTHER = 'Other',
}

export interface AppDocument {
  id: EntityId;
  fileName: string;
  mimeType: string;
  uploadDate: string; // ISO Date
  documentDate?: string; // ISO Date
  documentType: DocumentType;
  amount?: number;
  currency: string;
  propertyId?: EntityId;
  categoryId?: EntityId;
  counterpartyId?: EntityId;
  notes?: string;
  googleDriveId?: string; // Mock ID for now
  aiAnalysisRaw?: any;
}

export interface Transaction {
  id: EntityId;
  type: CategoryType;
  propertyId: EntityId;
  categoryId: EntityId;
  counterpartyId?: EntityId;
  amount: number;
  currency: string;
  date: string; // ISO Date
  description: string;
  documentId?: EntityId;
  isAutoGenerated?: boolean;
}

export interface RecurringPayment {
  id: EntityId;
  name: string;
  type: CategoryType;
  propertyId: EntityId;
  categoryId: EntityId;
  amount: number;
  frequency: 'MONTHLY' | 'QUARTERLY' | 'YEARLY';
  startDate: string;
  nextDueDate: string;
  active: boolean;
}

export interface AppSettings {
  googleDriveFolderId: string;
  currency: string;
  taxYear: number;
}
