/**
 * Automation Utilities Module
 * 
 * Shared utilities for all automation modules (mortgage, recurring, rent).
 * Extracts common functionality to reduce code duplication.
 * 
 * Note: Date utility functions (getLastDayOfMonth, getDaysInMonth) are in rent-automation.js
 */

const fs = require('fs');
const path = require('path');

/**
 * Source tags for tracking whether records were created by event-driven or batch processes
 */
const SOURCE_TAGS = {
  EVENT_DRIVEN_MORTGAGE: 'event-driven-mortgage',
  EVENT_DRIVEN_RECURRING: 'event-driven-recurring',
  EVENT_DRIVEN_RENT: 'event-driven-rent',
  BATCH_MORTGAGE: 'batch-mortgage',
  BATCH_RECURRING: 'batch-recurring',
  BATCH_RENT: 'batch-rent',
  MANUAL: 'manual'
};

/**
 * Valid automation types
 */
const VALID_AUTOMATION_TYPES = ['mortgage', 'recurring', 'rent'];

/**
 * Get the source tag for a specific automation type and mode
 * @param {string} automationType - 'mortgage', 'recurring', or 'rent'
 * @param {boolean} isEventDriven - True for event-driven, false for batch
 * @returns {string} Source tag
 * @throws {Error} If automationType is invalid
 */
function getSourceTag(automationType, isEventDriven) {
  if (!VALID_AUTOMATION_TYPES.includes(automationType)) {
    throw new Error(`Invalid automation type: ${automationType}. Valid types are: ${VALID_AUTOMATION_TYPES.join(', ')}`);
  }
  
  const typeMap = {
    mortgage: isEventDriven ? SOURCE_TAGS.EVENT_DRIVEN_MORTGAGE : SOURCE_TAGS.BATCH_MORTGAGE,
    recurring: isEventDriven ? SOURCE_TAGS.EVENT_DRIVEN_RECURRING : SOURCE_TAGS.BATCH_RECURRING,
    rent: isEventDriven ? SOURCE_TAGS.EVENT_DRIVEN_RENT : SOURCE_TAGS.BATCH_RENT
  };
  return typeMap[automationType] || SOURCE_TAGS.MANUAL;
}

/**
 * Check if a transaction was auto-generated by automation
 * @param {string} description - Transaction description
 * @returns {boolean} True if auto-generated
 */
function isAutoGeneratedTransaction(description) {
  if (!description) return false;
  
  const patterns = [
    /^Mortgage Payment:/i,
    /^Interest Payment:/i,
    /^Principal Payment:/i,
    /^Rent Payment:/i,
    /^Recurring Payment:/i,
    /Auto-generated/i,
    /^Amortization:/i
  ];
  
  return patterns.some(pattern => pattern.test(description));
}

/**
 * Format a date for use in descriptions
 * @param {Date|string} date - Date to format
 * @returns {string} Formatted date string (YYYY-MM)
 */
function formatDateForDescription(date) {
  const d = new Date(date);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`;
}

/**
 * Format a date for database storage
 * @param {Date|string} date - Date to format
 * @returns {string} ISO date string (YYYY-MM-DD)
 */
function formatDateForDB(date) {
  const d = new Date(date);
  return d.toISOString().split('T')[0];
}

/**
 * Calculate months between two dates
 * @param {Date|string} startDate - Start date
 * @param {Date|string} endDate - End date
 * @returns {number} Number of months between dates
 */
function getMonthsBetweenDates(startDate, endDate) {
  const start = new Date(startDate);
  const end = new Date(endDate);
  return (end.getUTCFullYear() - start.getUTCFullYear()) * 12 +
         (end.getUTCMonth() - start.getUTCMonth());
}

/**
 * Normalize a value for comparison
 * Handles null/undefined, converts dates to ISO strings
 * Preserves number types (does not convert to string)
 * @param {*} value - The value to normalize
 * @returns {*} Normalized value for comparison
 */
function normalizeValue(value) {
  if (value === null || value === undefined) {
    return null;
  }
  
  if (value instanceof Date) {
    return value.toISOString();
  }
  
  return value;
}

/**
 * Get the last day of a month (delegates to rent-automation.js to avoid duplication)
 * @param {Date|string} date - Any date in the target month
 * @returns {Date} Date object set to the last day of the month
 */
function getLastDayOfMonth(date) {
  const { getLastDayOfMonth: rentGetLastDayOfMonth } = require('./rent-automation');
  return rentGetLastDayOfMonth(date);
}

/**
 * Get number of days in a month (delegates to rent-automation.js to avoid duplication)
 * @param {number} year - Year
 * @param {number} month - Month (0-11)
 * @returns {number} Number of days in the month
 */
function getDaysInMonth(year, month) {
  const { getDaysInMonth: rentGetDaysInMonth } = require('./rent-automation');
  return rentGetDaysInMonth(year, month);
}

/**
 * Ensure logs directory exists
 * @returns {void}
 */
function ensureLogsDir() {
  const logsDir = path.join(__dirname, 'logs');
  if (!fs.existsSync(logsDir)) {
    try {
      fs.mkdirSync(logsDir, { recursive: true });
    } catch (err) {
      console.error('Failed to create logs directory:', err.message);
    }
  }
}

/**
 * Log an automation action with source tag
 * @param {string} message - Log message
 * @param {string} source - Source tag
 * @param {object} [context] - Additional context
 */
function logAutomationAction(message, source, context = {}) {
  try {
    ensureLogsDir();
    const timestamp = new Date().toISOString();
    const contextStr = Object.keys(context).length > 0 ? ` | ${JSON.stringify(context)}` : '';
    const fullMessage = `${timestamp} | [${source}] ${message}${contextStr}`;
    console.log(fullMessage);
    
    try {
      fs.appendFileSync(
        path.join(__dirname, 'logs', 'automation.log'),
        fullMessage + '\n'
      );
    } catch (err) {
      console.error('Failed to write to automation log:', err.message);
    }
  } catch (err) {
    console.error('Error in logAutomationAction:', err.message);
  }
}

/**
 * Log an automation error with source tag
 * @param {Error} error - Error object
 * @param {string} source - Source tag
 * @param {object} [context] - Additional context
 */
function logAutomationError(error, source, context = {}) {
  try {
    ensureLogsDir();
    const timestamp = new Date().toISOString();
    const contextStr = Object.keys(context).length > 0 ? ` | ${JSON.stringify(context)}` : '';
    const fullMessage = `${timestamp} | ERROR | [${source}] ${error.message}${contextStr}\n${error.stack}`;
    console.error(fullMessage);
    
    try {
      fs.appendFileSync(
        path.join(__dirname, 'logs', 'automation-errors.log'),
        fullMessage + '\n\n'
      );
    } catch (err) {
      console.error('Failed to write to automation errors log:', err.message);
    }
  } catch (err) {
    console.error('Error in logAutomationError:', err.message);
  }
}

/**
 * Wrap an async function with error handling and logging
 * @param {string} source - Source tag
 * @param {string} contextStr - Context string for logging
 * @param {Function} fn - Async function to wrap
 * @returns {Function} Wrapped function
 */
function withErrorHandling(source, contextStr) {
  return async function(...args) {
    try {
      const result = await fn.apply(this, args);
      logAutomationAction(`${contextStr}: Success`, source);
      return result;
    } catch (error) {
      logAutomationError(error, source, { context: contextStr });
      throw error;
    }
  };
}

/**
 * Check if a feature flag is enabled
 * @param {string} flagName - Feature flag name (EVENT_DRIVEN_MORTGAGE, etc.)
 * @returns {boolean} True if flag is enabled
 */
function isFeatureEnabled(flagName) {
  const flagValue = process.env[flagName];
  return flagValue === 'true' || flagValue === '1';
}

/**
 * Get all categories from database (requires db parameter)
 * @param {object} db - Database connection
 * @returns {Promise<Array>} Array of category objects
 */
async function getAllCategories(db) {
  return new Promise((resolve, reject) => {
    db.all('SELECT * FROM categories', [], (err, rows) => {
      if (err) {
        return reject(err);
      }
      resolve(rows);
    });
  });
}

/**
 * Get a category by ID (requires db parameter)
 * @param {object} db - Database connection
 * @param {number} categoryId - Category ID
 * @returns {Promise<object|null>} Category object or null
 */
async function getCategoryById(db, categoryId) {
  return new Promise((resolve, reject) => {
    db.get('SELECT * FROM categories WHERE id = ?', [categoryId], (err, row) => {
      if (err) {
        return reject(err);
      }
      resolve(row || null);
    });
  });
}

/**
 * Find or create a category by name (requires db parameter)
 * @param {object} db - Database connection
 * @param {string} name - Category name
 * @param {string} type - Category type ('INCOME' or 'EXPENSE')
 * @param {number} isTaxRelevant - Whether tax relevant (0 or 1)
 * @returns {Promise<object>} Category object with id, name, type
 */
async function findOrCreateCategory(db, name, type = 'EXPENSE', isTaxRelevant = 0) {
  return new Promise((resolve, reject) => {
    db.get(
      'SELECT * FROM categories WHERE name = ? AND type = ?',
      [name, type],
      (err, row) => {
        if (err) {
          return reject(err);
        }
        
        if (row) {
          return resolve(row);
        }
        
        db.run(
          'INSERT INTO categories (name, type, isTaxRelevant) VALUES (?, ?, ?)',
          [name, type, isTaxRelevant],
          function(err) {
            if (err) {
              return reject(err);
            }
            resolve({
              id: this.lastID,
              name: name,
              type: type,
              isTaxRelevant: isTaxRelevant
            });
          }
        );
      }
    );
  });
}

module.exports = {
  SOURCE_TAGS,
  VALID_AUTOMATION_TYPES,
  getSourceTag,
  isAutoGeneratedTransaction,
  formatDateForDescription,
  formatDateForDB,
  getMonthsBetweenDates,
  normalizeValue,
  getLastDayOfMonth,
  getDaysInMonth,
  ensureLogsDir,
  logAutomationAction,
  logAutomationError,
  withErrorHandling,
  isFeatureEnabled,
  getAllCategories,
  getCategoryById,
  findOrCreateCategory
};
