/**
 * Automation Utilities Module
 * 
 * Shared utilities for all automation modules (mortgage, recurring, rent).
 * Extracts common functionality to reduce code duplication.
 */

const path = require('path');
const sqlite3 = require('sqlite3').verbose();
const dbPath = path.join(__dirname, 'immopi.db');
const db = new sqlite3.Database(dbPath);

/**
 * Source tags for tracking whether records were created by event-driven or batch processes
 */
const SOURCE_TAGS = {
  EVENT_DRIVEN_MORTGAGE: 'event-driven-mortgage',
  EVENT_DRIVEN_RECURRING: 'event-driven-recurring',
  EVENT_DRIVEN_RENT: 'event-driven-rent',
  BATCH_MORTGAGE: 'batch-mortgage',
  BATCH_RECURRING: 'batch-recurring',
  BATCH_RENT: 'batch-rent',
  MANUAL: 'manual'
};

/**
 * Get the source tag for a specific automation type and mode
 * @param {string} automationType - 'mortgage', 'recurring', or 'rent'
 * @param {boolean} isEventDriven - True for event-driven, false for batch
 * @returns {string} Source tag
 */
function getSourceTag(automationType, isEventDriven) {
  const typeMap = {
    mortgage: isEventDriven ? SOURCE_TAGS.EVENT_DRIVEN_MORTGAGE : SOURCE_TAGS.BATCH_MORTGAGE,
    recurring: isEventDriven ? SOURCE_TAGS.EVENT_DRIVEN_RECURRING : SOURCE_TAGS.BATCH_RECURRING,
    rent: isEventDriven ? SOURCE_TAGS.EVENT_DRIVEN_RENT : SOURCE_TAGS.BATCH_RENT
  };
  return typeMap[automationType] || SOURCE_TAGS.MANUAL;
}

/**
 * Check if a transaction was auto-generated by automation
 * @param {string} description - Transaction description
 * @returns {boolean} True if auto-generated
 */
function isAutoGeneratedTransaction(description) {
  if (!description) return false;
  
  // Check for common auto-generated patterns
  const patterns = [
    /^Mortgage Payment:/i,
    /^Interest Payment:/i,
    /^Principal Payment:/i,
    /^Rent Payment:/i,
    /^Recurring Payment:/i,
    /Auto-generated/i,
    /^Amortization:/i
  ];
  
  return patterns.some(pattern => pattern.test(description));
}

/**
 * Format a date for use in descriptions and database
 * @param {Date|string} date - Date to format
 * @returns {string} Formatted date string (YYYY-MM)
 */
function formatDateForDescription(date) {
  const d = new Date(date);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`;
}

/**
 * Format a date for database storage
 * @param {Date|string} date - Date to format
 * @returns {string} ISO date string (YYYY-MM-DD)
 */
function formatDateForDB(date) {
  const d = new Date(date);
  return d.toISOString().split('T')[0];
}

/**
 * Get the last day of a month
 * @param {Date|string} date - Any date in the target month
 * @returns {Date} Date object set to the last day of the month
 */
function getLastDayOfMonth(date) {
  const d = new Date(date);
  const year = d.getUTCFullYear();
  const month = d.getUTCMonth();
  // Set to first day of next month, then subtract 1 day
  const firstDayOfNextMonth = new Date(Date.UTC(year, month + 1, 1));
  const lastDay = new Date(firstDayOfNextMonth.getTime() - 24 * 60 * 60 * 1000);
  return lastDay;
}

/**
 * Get number of days in a month
 * @param {number} year - Year
 * @param {number} month - Month (0-11)
 * @returns {number} Number of days in the month
 */
function getDaysInMonth(year, month) {
  return new Date(Date.UTC(year, month + 1, 0)).getUTCDate();
}

/**
 * Calculate months between two dates
 * @param {Date|string} startDate - Start date
 * @param {Date|string} endDate - End date
 * @returns {number} Number of months between dates
 */
function getMonthsBetweenDates(startDate, endDate) {
  const start = new Date(startDate);
  const end = new Date(endDate);
  return (end.getUTCFullYear() - start.getUTCFullYear()) * 12 +
         (end.getUTCMonth() - start.getUTCMonth());
}

/**
 * Find or create a category by name
 * @param {string} name - Category name
 * @param {string} type - Category type ('INCOME' or 'EXPENSE')
 * @param {number} isTaxRelevant - Whether tax relevant (0 or 1)
 * @returns {Promise<object>} Category object with id, name, type
 */
async function findOrCreateCategory(name, type = 'EXPENSE', isTaxRelevant = 0) {
  return new Promise((resolve, reject) => {
    // First, try to find existing category
    db.get(
      'SELECT * FROM categories WHERE name = ? AND type = ?',
      [name, type],
      (err, row) => {
        if (err) {
          return reject(err);
        }
        
        if (row) {
          return resolve(row);
        }
        
        // Create new category
        db.run(
          'INSERT INTO categories (name, type, isTaxRelevant) VALUES (?, ?, ?)',
          [name, type, isTaxRelevant],
          function(err) {
            if (err) {
              return reject(err);
            }
            resolve({
              id: this.lastID,
              name: name,
              type: type,
              isTaxRelevant: isTaxRelevant
            });
          }
        );
      }
    );
  });
}

/**
 * Log an automation action with source tag
 * @param {string} message - Log message
 * @param {string} source - Source tag
 * @param {object} [context] - Additional context
 */
function logAutomationAction(message, source, context = {}) {
  const timestamp = new Date().toISOString();
  const contextStr = Object.keys(context).length > 0 ? ` | ${JSON.stringify(context)}` : '';
  const fullMessage = `${timestamp} | [${source}] ${message}${contextStr}`;
  console.log(fullMessage);
  
  // Also write to automation log file
  const fs = require('fs');
  const path = require('path');
  const logsDir = path.join(__dirname, 'logs');
  if (!fs.existsSync(logsDir)) {
    fs.mkdirSync(logsDir, { recursive: true });
  }
  fs.appendFileSync(
    path.join(logsDir, 'automation.log'),
    fullMessage + '\n'
  );
}

/**
 * Log an automation error with source tag
 * @param {Error} error - Error object
 * @param {string} source - Source tag
 * @param {object} [context] - Additional context
 */
function logAutomationError(error, source, context = {}) {
  const timestamp = new Date().toISOString();
  const contextStr = Object.keys(context).length > 0 ? ` | ${JSON.stringify(context)}` : '';
  const fullMessage = `${timestamp} | ERROR | [${source}] ${error.message}${contextStr}\n${error.stack}`;
  console.error(fullMessage);
  
  const fs = require('fs');
  const path = require('path');
  const logsDir = path.join(__dirname, 'logs');
  if (!fs.existsSync(logsDir)) {
    fs.mkdirSync(logsDir, { recursive: true });
  }
  fs.appendFileSync(
    path.join(logsDir, 'automation-errors.log'),
    fullMessage + '\n\n'
  );
}

/**
 * Wrap an async function with error handling and logging
 * @param {string} source - Source tag
 * @param {string} contextStr - Context string for logging
 * @param {Function} fn - Async function to wrap
 * @returns {Function} Wrapped function
 */
function withErrorHandling(source, contextStr) {
  return async function(...args) {
    try {
      const result = await fn.apply(this, args);
      logAutomationAction(`${contextStr}: Success`, source);
      return result;
    } catch (error) {
      logAutomationError(error, source, { context: contextStr });
      throw error;
    }
  };
}

/**
 * Check if a feature flag is enabled
 * @param {string} flagName - Feature flag name (EVENT_DRIVEN_MORTGAGE, etc.)
 * @returns {boolean} True if flag is enabled
 */
function isFeatureEnabled(flagName) {
  const flagValue = process.env[flagName];
  return flagValue === 'true' || flagValue === '1';
}

/**
 * Get all categories from database
 * @returns {Promise<Array>} Array of category objects
 */
async function getAllCategories() {
  return new Promise((resolve, reject) => {
    db.all('SELECT * FROM categories', [], (err, rows) => {
      if (err) {
        return reject(err);
      }
      resolve(rows);
    });
  });
}

/**
 * Get a category by ID
 * @param {number} categoryId - Category ID
 * @returns {Promise<object|null>} Category object or null
 */
async function getCategoryById(categoryId) {
  return new Promise((resolve, reject) => {
    db.get('SELECT * FROM categories WHERE id = ?', [categoryId], (err, row) => {
      if (err) {
        return reject(err);
      }
      resolve(row || null);
    });
  });
}

module.exports = {
  SOURCE_TAGS,
  getSourceTag,
  isAutoGeneratedTransaction,
  formatDateForDescription,
  formatDateForDB,
  getLastDayOfMonth,
  getDaysInMonth,
  getMonthsBetweenDates,
  findOrCreateCategory,
  logAutomationAction,
  logAutomationError,
  withErrorHandling,
  isFeatureEnabled,
  getAllCategories,
  getCategoryById
};
