import React, { useEffect, useState } from 'react';
import { Card, Button } from '../components/ui';
import { db } from '../services/storage';
import { Transaction, Property, CategoryType, RecurringPayment } from '../types';
import { ArrowUpRight, ArrowDownRight, Euro, Activity, AlertCircle, Landmark, RefreshCcw } from 'lucide-react';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, 
  PieChart, Pie, Legend 
} from 'recharts';

const COLORS = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#f97316'];

const StatCard = ({ title, value, type, icon: Icon }: { title: string; value: string; type: 'neutral' | 'positive' | 'negative'; icon: any }) => (
  <Card className="p-6">
    <div className="flex items-center justify-between">
      <div>
        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{title}</p>
        <p className={`text-2xl font-bold mt-1 ${type === 'positive' ? 'text-emerald-600' : type === 'negative' ? 'text-rose-600' : 'text-slate-900'}`}>
          {value}
        </p>
      </div>
      <div className={`p-3 rounded-xl ${type === 'positive' ? 'bg-emerald-50 text-emerald-600' : type === 'negative' ? 'bg-rose-50 text-rose-600' : 'bg-blue-50 text-blue-600'}`}>
        <Icon className="w-5 h-5" />
      </div>
    </div>
  </Card>
);

export const Dashboard = () => {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [properties, setProperties] = useState<Property[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [year, setYear] = useState(new Date().getFullYear());
  const [automationLog, setAutomationLog] = useState<string[]>([]);
  const [isRefreshing, setIsRefreshing] = useState(false);

  const runAutomation = () => {
    setIsRefreshing(true);
    const logs: string[] = [];
    
    // Process Recurring
    logs.push(...processRecurringPayments());
    
    // Process Mortgages using centralized logic
    const props = db.getProperties();
    props.forEach(p => {
      const mortgageLogs = db.syncMortgageTransactions(p, year);
      logs.push(...mortgageLogs);
    });
    
    if (logs.length > 0) {
      setAutomationLog(logs);
    }
    
    setTransactions(db.getTransactions());
    setProperties(props);
    setTimeout(() => setIsRefreshing(false), 600);
  };

  useEffect(() => {
    runAutomation();
    setCategories(db.getCategories());
  }, [year]);

  const processRecurringPayments = () => {
    const recurring = db.getRecurringPayments();
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const logs: string[] = [];

    recurring.filter(r => r.active).forEach(r => {
      let nextDue = new Date(r.nextDueDate);
      while (nextDue <= today && nextDue.getFullYear() === year) {
        db.saveTransaction({
          type: r.type,
          propertyId: r.propertyId,
          categoryId: r.categoryId,
          amount: r.amount,
          currency: 'EUR',
          date: nextDue.toISOString().split('T')[0],
          description: `Recurring: ${r.name}`,
          isAutoGenerated: true
        });

        logs.push(`Recurring: ${r.name} (${nextDue.toLocaleDateString()})`);

        if (r.frequency === 'MONTHLY') nextDue.setMonth(nextDue.getMonth() + 1);
        else if (r.frequency === 'QUARTERLY') nextDue.setMonth(nextDue.getMonth() + 3);
        else if (r.frequency === 'YEARLY') nextDue.setFullYear(nextDue.getFullYear() + 1);
        
        r.nextDueDate = nextDue.toISOString().split('T')[0];
      }
      db.saveRecurringPayment(r);
    });
    return logs;
  };

  // KPI Logic: Year to Date
  const todayDate = new Date();
  const currentYearTransactions = transactions.filter(t => {
    const txDate = new Date(t.date);
    if (year === todayDate.getFullYear()) {
      return txDate.getFullYear() === year && txDate <= todayDate;
    }
    return txDate.getFullYear() === year;
  });
  
  const totalIncome = currentYearTransactions
    .filter(t => t.type === CategoryType.INCOME)
    .reduce((sum, t) => sum + t.amount, 0);

  const totalExpense = currentYearTransactions
    .filter(t => t.type === CategoryType.EXPENSE)
    .reduce((sum, t) => sum + t.amount, 0);

  const netResult = totalIncome - totalExpense;

  const monthlyData = Array.from({ length: 12 }, (_, i) => {
    const monthTx = transactions.filter(t => {
      const d = new Date(t.date);
      return d.getFullYear() === year && d.getMonth() === i;
    });
    return {
      name: new Date(year, i, 1).toLocaleString('default', { month: 'short' }),
      Income: monthTx.filter(t => t.type === CategoryType.INCOME).reduce((s, t) => s + t.amount, 0),
      Expense: monthTx.filter(t => t.type === CategoryType.EXPENSE).reduce((s, t) => s + t.amount, 0)
    };
  });

  const expenseData = categories
    .filter(c => c.type === CategoryType.EXPENSE)
    .map(c => ({
      name: c.name,
      value: currentYearTransactions.filter(t => t.categoryId === c.id).reduce((s, t) => s + t.amount, 0)
    }))
    .filter(d => d.value > 0);

  const propertyIncomeData = properties.map(p => ({
    name: p.name,
    income: currentYearTransactions
      .filter(t => t.propertyId === p.id && t.type === CategoryType.INCOME)
      .reduce((s, t) => s + t.amount, 0)
  })).sort((a, b) => b.income - a.income);

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Financial Dashboard</h1>
          <p className="text-slate-500 text-sm font-medium">Real-time Performance Analysis for {year}</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="secondary" onClick={runAutomation} loading={isRefreshing} className="bg-white">
            <RefreshCcw className={`w-4 h-4 mr-2 ${isRefreshing ? 'animate-spin' : ''}`} />
            Refresh Data
          </Button>
          <select 
            value={year} 
            onChange={(e) => setYear(Number(e.target.value))}
            className="bg-white border border-slate-200 rounded-xl px-4 py-2 text-sm font-semibold focus:ring-2 focus:ring-blue-500 outline-none shadow-sm"
          >
            {[0, 1, 2, 3, 4, 5].map(i => (
              <option key={i} value={new Date().getFullYear() - i}>{new Date().getFullYear() - i}</option>
            ))}
          </select>
        </div>
      </div>

      {automationLog.length > 0 && (
        <Card className="p-4 bg-emerald-50 border-emerald-100 flex items-start gap-4 animate-in slide-in-from-top duration-500">
          <div className="p-2 bg-white rounded-lg text-emerald-600 shadow-sm">
            <AlertCircle className="w-5 h-5" />
          </div>
          <div className="flex-1">
            <h4 className="text-sm font-bold text-emerald-900">Automation Summary</h4>
            <p className="text-xs text-emerald-700 leading-relaxed mt-1">
              Synchronized {automationLog.length} scheduled transactions, including interest and principal splits.
            </p>
          </div>
          <button onClick={() => setAutomationLog([])} className="p-2 hover:bg-emerald-100 rounded-lg transition-colors text-emerald-400">
            <Euro className="w-4 h-4" />
          </button>
        </Card>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <StatCard title="Income YTD" value={`€${totalIncome.toLocaleString(undefined, { minimumFractionDigits: 2 })}`} type="positive" icon={ArrowUpRight} />
        <StatCard title="Expenses YTD" value={`€${totalExpense.toLocaleString(undefined, { minimumFractionDigits: 2 })}`} type="negative" icon={ArrowDownRight} />
        <StatCard title="Net Profit YTD" value={`€${netResult.toLocaleString(undefined, { minimumFractionDigits: 2 })}`} type={netResult >= 0 ? 'positive' : 'negative'} icon={Euro} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="p-6 lg:col-span-2">
          <div className="flex items-center justify-between mb-8">
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest">Monthly Cash Flow</h3>
            <div className="flex gap-4 text-xs font-bold">
              <span className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-emerald-500" /> Income</span>
              <span className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-rose-500" /> Expense</span>
            </div>
          </div>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={monthlyData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#94a3b8', fontWeight: 600 }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#94a3b8', fontWeight: 600 }} tickFormatter={(val) => `€${val}`} />
                <Tooltip 
                  cursor={{ fill: '#f8fafc' }}
                  contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)', fontSize: '12px' }}
                />
                <Bar dataKey="Income" fill="#10b981" radius={[4, 4, 0, 0]} barSize={24} />
                <Bar dataKey="Expense" fill="#f43f5e" radius={[4, 4, 0, 0]} barSize={24} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Card>

        <Card className="p-6">
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-8">Tax Categories YTD</h3>
          <div className="h-80">
            {expenseData.length > 0 ? (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={expenseData}
                    innerRadius={70}
                    outerRadius={100}
                    paddingAngle={8}
                    dataKey="value"
                    stroke="none"
                  >
                    {expenseData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip 
                     contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)', fontSize: '12px' }}
                  />
                  <Legend verticalAlign="bottom" height={40} iconType="circle" wrapperStyle={{ fontSize: '11px', fontWeight: 600, color: '#64748b', paddingTop: '20px' }} />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-slate-400 text-sm gap-2">
                <Activity className="w-8 h-8 opacity-20" />
                <span>No expense data recorded.</span>
              </div>
            )}
          </div>
        </Card>

        <Card className="p-6 lg:col-span-1">
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-8">Yield per Property</h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={propertyIncomeData} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f1f5f9" />
                <XAxis type="number" hide />
                <YAxis dataKey="name" type="category" width={100} axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#64748b', fontWeight: 600 }} />
                <Tooltip />
                <Bar dataKey="income" fill="#3b82f6" radius={[0, 4, 4, 0]} barSize={16} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Card>

        <Card className="p-6 lg:col-span-2">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest">Recent Activity</h3>
            <Activity className="w-4 h-4 text-slate-400" />
          </div>
          <div className="space-y-4">
            {transactions.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()).slice(0, 5).map(t => (
              <div key={t.id} className="flex items-center justify-between p-4 hover:bg-slate-50 rounded-2xl transition-all border border-transparent hover:border-slate-100 group">
                <div className="flex items-center gap-4">
                  <div className={`p-3 rounded-xl transition-colors ${t.type === CategoryType.INCOME ? 'bg-emerald-50 text-emerald-600 group-hover:bg-emerald-100' : 'bg-rose-50 text-rose-600 group-hover:bg-rose-100'}`}>
                    {t.categoryId === 'c9' || t.categoryId === 'c10' ? <Landmark className="w-4 h-4" /> : <Activity className="w-4 h-4" />}
                  </div>
                  <div>
                    <p className="text-sm font-bold text-slate-900 leading-tight">{t.description}</p>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">
                        {new Date(t.date).toLocaleDateString('de-DE')}
                      </span>
                      {t.isAutoGenerated && (
                        <span className="text-[10px] bg-blue-50 text-blue-600 px-1.5 py-0.5 rounded font-bold">AUTOMATED</span>
                      )}
                    </div>
                  </div>
                </div>
                <span className={`font-black text-sm tracking-tight ${t.type === CategoryType.INCOME ? 'text-emerald-600' : 'text-slate-700'}`}>
                  {t.type === CategoryType.INCOME ? '+' : '-'}€{t.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </span>
              </div>
            ))}
          </div>
        </Card>
      </div>
    </div>
  );
};