/**
 * Event-Driven Automation Integration Tests
 * 
 * Tests for verifying that event-driven automation works correctly.
 * Tests all three automation types: mortgage, recurring, and rent.
 */

const assert = require('assert');
const { hasMortgageChanged, hasMortgageData, hasPaymentTermsChanged, hasRecurringPaymentChanged, shouldTriggerAutomation } = require('../event-detector');
const { SOURCE_TAGS, getSourceTag, isAutoGeneratedTransaction } = require('../automation-utils');

// Simple test runner that actually executes the tests
function runTests() {
  console.log('Running Event-Driven Automation Tests...\n');
  
  const testSuites = [
    {
      name: 'Phase 1: Event Detector',
      tests: [
        // hasMortgageData tests
        {
          name: 'hasMortgageData should return true for property with mortgage data',
          test: () => {
            const property = {
              mortgage_loanAmount: 200000,
              mortgage_startDate: '2025-01-01',
              mortgage_interestRate: 3.5,
              mortgage_principalRate: 2.0
            };
            assert.strictEqual(hasMortgageData(property), true);
          }
        },
        {
          name: 'hasMortgageData should return false for property without mortgage data',
          test: () => {
            const property = {
              name: 'Test Property',
              purchasePrice: 300000
            };
            assert.strictEqual(hasMortgageData(property), false);
          }
        },
        {
          name: 'hasMortgageData should return false for null property',
          test: () => {
            assert.strictEqual(hasMortgageData(null), false);
          }
        },
        // hasMortgageChanged tests
        {
          name: 'hasMortgageChanged should return true when creating new property with mortgage',
          test: () => {
            const newProperty = {
              mortgage_loanAmount: 200000,
              mortgage_startDate: '2025-01-01'
            };
            assert.strictEqual(hasMortgageChanged(newProperty, null), true);
          }
        },
        {
          name: 'hasMortgageChanged should return true when mortgage amount changes',
          test: () => {
            const oldProperty = { mortgage_loanAmount: 200000 };
            const newProperty = { mortgage_loanAmount: 250000 };
            assert.strictEqual(hasMortgageChanged(newProperty, oldProperty), true);
          }
        },
        {
          name: 'hasMortgageChanged should return false when mortgage data is unchanged',
          test: () => {
            const property = {
              mortgage_loanAmount: 200000,
              mortgage_startDate: '2025-01-01'
            };
            assert.strictEqual(hasMortgageChanged(property, property), false);
          }
        },
        // hasPaymentTermsChanged tests
        {
          name: 'hasPaymentTermsChanged should return true when creating new contract',
          test: () => {
            const newContract = { coldRent: 1000, sideCosts: 200 };
            assert.strictEqual(hasPaymentTermsChanged(newContract, null), true);
          }
        },
        {
          name: 'hasPaymentTermsChanged should return true when cold rent changes',
          test: () => {
            const oldContract = { coldRent: 1000, sideCosts: 200 };
            const newContract = { coldRent: 1200, sideCosts: 200 };
            assert.strictEqual(hasPaymentTermsChanged(newContract, oldContract), true);
          }
        },
        {
          name: 'hasPaymentTermsChanged should return false when payment terms are unchanged',
          test: () => {
            const contract = { coldRent: 1000, sideCosts: 200 };
            assert.strictEqual(hasPaymentTermsChanged(contract, contract), false);
          }
        },
        // hasRecurringPaymentChanged tests
        {
          name: 'hasRecurringPaymentChanged should return true when creating new recurring payment',
          test: () => {
            const newRecurring = { amount: 500, frequency: 'monthly' };
            assert.strictEqual(hasRecurringPaymentChanged(newRecurring, null), true);
          }
        },
        {
          name: 'hasRecurringPaymentChanged should return true when amount changes',
          test: () => {
            const oldRecurring = { amount: 500, frequency: 'monthly' };
            const newRecurring = { amount: 600, frequency: 'monthly' };
            assert.strictEqual(hasRecurringPaymentChanged(newRecurring, oldRecurring), true);
          }
        },
        {
          name: 'hasRecurringPaymentChanged should return false when recurring payment is unchanged',
          test: () => {
            const recurring = { amount: 500, frequency: 'monthly' };
            assert.strictEqual(hasRecurringPaymentChanged(recurring, recurring), false);
          }
        },
        // shouldTriggerAutomation tests
        {
          name: 'shouldTriggerAutomation should trigger mortgage automation for new property with mortgage',
          test: () => {
            const newProperty = { mortgage_loanAmount: 200000 };
            const result = shouldTriggerAutomation('property', newProperty, null);
            assert.strictEqual(result.trigger, true);
            assert.strictEqual(result.changeType, 'create');
          }
        },
        {
          name: 'shouldTriggerAutomation should not trigger mortgage automation for property without mortgage',
          test: () => {
            const newProperty = { name: 'Test' };
            const result = shouldTriggerAutomation('property', newProperty, null);
            assert.strictEqual(result.trigger, false);
          }
        },
        {
          name: 'shouldTriggerAutomation should trigger mortgage automation when mortgage changes',
          test: () => {
            const oldProperty = { mortgage_loanAmount: 200000 };
            const newProperty = { mortgage_loanAmount: 250000 };
            const result = shouldTriggerAutomation('property', newProperty, oldProperty);
            assert.strictEqual(result.trigger, true);
            assert.strictEqual(result.changeType, 'update');
          }
        }
      ]
    },
    {
      name: 'Phase 1: Automation Utils',
      tests: [
        // SOURCE_TAGS tests
        {
          name: 'SOURCE_TAGS should have all required source tags',
          test: () => {
            assert.ok(SOURCE_TAGS.EVENT_DRIVEN_MORTGAGE);
            assert.ok(SOURCE_TAGS.EVENT_DRIVEN_RECURRING);
            assert.ok(SOURCE_TAGS.EVENT_DRIVEN_RENT);
            assert.ok(SOURCE_TAGS.BATCH_MORTGAGE);
            assert.ok(SOURCE_TAGS.BATCH_RECURRING);
            assert.ok(SOURCE_TAGS.BATCH_RENT);
            assert.ok(SOURCE_TAGS.MANUAL);
          }
        },
        // getSourceTag tests
        {
          name: 'getSourceTag should return event-driven tag for mortgage when isEventDriven is true',
          test: () => {
            const tag = getSourceTag('mortgage', true);
            assert.strictEqual(tag, SOURCE_TAGS.EVENT_DRIVEN_MORTGAGE);
          }
        },
        {
          name: 'getSourceTag should return batch tag for mortgage when isEventDriven is false',
          test: () => {
            const tag = getSourceTag('mortgage', false);
            assert.strictEqual(tag, SOURCE_TAGS.BATCH_MORTGAGE);
          }
        },
        {
          name: 'getSourceTag should return event-driven tag for rent',
          test: () => {
            const tag = getSourceTag('rent', true);
            assert.strictEqual(tag, SOURCE_TAGS.EVENT_DRIVEN_RENT);
          }
        },
        {
          name: 'getSourceTag should return event-driven tag for recurring',
          test: () => {
            const tag = getSourceTag('recurring', true);
            assert.strictEqual(tag, SOURCE_TAGS.EVENT_DRIVEN_RECURRING);
          }
        },
        // isAutoGeneratedTransaction tests
        {
          name: 'isAutoGeneratedTransaction should return true for mortgage payment description',
          test: () => {
            assert.strictEqual(isAutoGeneratedTransaction('Mortgage Payment: Property 1 - Jan 2025'), true);
          }
        },
        {
          name: 'isAutoGeneratedTransaction should return true for rent payment description',
          test: () => {
            assert.strictEqual(isAutoGeneratedTransaction('Rent Payment: Property A - Jan 2025'), true);
          }
        },
        {
          name: 'isAutoGeneratedTransaction should return false for manual description',
          test: () => {
            assert.strictEqual(isAutoGeneratedTransaction('Manual payment from tenant'), false);
          }
        },
        {
          name: 'isAutoGeneratedTransaction should return false for null description',
          test: () => {
            assert.strictEqual(isAutoGeneratedTransaction(null), false);
          }
        }
      ]
    }
  ];
  
  let passed = 0;
  let failed = 0;
  const failures = [];
  
  for (const suite of testSuites) {
    console.log(`\n📋 ${suite.name}`);
    console.log('─'.repeat(50));
    
    for (const test of suite.tests) {
      try {
        test.test();
        console.log(`   ✅ ${test.name}`);
        passed++;
      } catch (error) {
        console.log(`   ❌ ${test.name}`);
        console.log(`      Error: ${error.message}`);
        failed++;
        failures.push({ suite: suite.name, test: test.name, error: error.message });
      }
    }
  }
  
  console.log(`\n${'='.repeat(60)}`);
  console.log(`📊 Test Results:`);
  console.log(`   ✅ Passed: ${passed}`);
  console.log(`   ❌ Failed: ${failed}`);
  
  if (failures.length > 0) {
    console.log(`\n🔍 Failures:`);
    failures.forEach(failure => {
      console.log(`   - ${failure.suite} > ${failure.test}: ${failure.error}`);
    });
  }
  
  if (failed === 0) {
    console.log(`\n✅ All Phase 1 tests passed!`);
  } else {
    console.log(`\n❌ Some tests failed. Please review the failures above.`);
    process.exit(1);
  }
  
  return { passed, failed, failures };
}

// Run tests if this file is executed directly
if (require.main === module) {
  runTests();
}

module.exports = {
  // Export test runner for use in other test files
  runTests
};
