/**
 * Test Setup Module
 * 
 * Sets up isolated test environment for event-driven automation tests.
 * Creates test databases and test data for each phase.
 */

const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const fs = require('fs');

// Test database path
const TEST_DB_PATH = path.join(__dirname, 'test-immopi.db');

// In-memory database for fast tests (alternative)
// const TEST_DB_PATH = ':memory:';

let testDb = null;

/**
 * Create a fresh test database
 * @returns {Promise<sqlite3.Database>} Test database instance
 */
async function createTestDatabase() {
  return new Promise((resolve, reject) => {
    // Close existing test database if open
    if (testDb) {
      testDb.close();
    }
    
    // Remove old test database file
    if (fs.existsSync(TEST_DB_PATH)) {
      fs.unlinkSync(TEST_DB_PATH);
    }
    
    // Create new test database
    testDb = new sqlite3.Database(TEST_DB_PATH, (err) => {
      if (err) {
        return reject(err);
      }
      resolve(testDb);
    });
  });
}

/**
 * Initialize test database schema
 * @returns {Promise<void>}
 */
async function initializeTestSchema() {
  const db = testDb || (await createTestDatabase());
  
  return new Promise((resolve, reject) => {
    db.serialize(() => {
      // Create properties table
      db.run(`
        CREATE TABLE IF NOT EXISTS properties (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          address TEXT,
          type TEXT,
          purchasePrice REAL,
          purchaseDate TEXT,
          rentAmount REAL,
          size REAL,
          mortgage_loanAmount REAL,
          mortgage_startDate TEXT,
          mortgage_interestRate REAL,
          mortgage_principalRate REAL,
          mortgage_bankName TEXT,
          mortgage_paymentTiming TEXT,
          notes TEXT,
          createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
          updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
        )
      `, (err) => { if (err) return reject(err); });

      // Create tenants table
      db.run(`
        CREATE TABLE IF NOT EXISTS tenants (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          email TEXT,
          phone TEXT,
          address TEXT,
          notes TEXT,
          createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
          updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
        )
      `, (err) => { if (err) return reject(err); });

      // Create categories table
      db.run(`
        CREATE TABLE IF NOT EXISTS categories (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          type TEXT NOT NULL,
          isTaxRelevant INTEGER DEFAULT 0,
          createdAt TEXT DEFAULT CURRENT_TIMESTAMP
        )
      `, (err) => { if (err) return reject(err); });

      // Create transactions table
      db.run(`
        CREATE TABLE IF NOT EXISTS transactions (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          date TEXT NOT NULL,
          amount REAL NOT NULL,
          currency TEXT DEFAULT 'EUR',
          description TEXT,
          type TEXT NOT NULL,
          property_id INTEGER,
          category_id INTEGER,
          counterparty_id INTEGER,
          document_id INTEGER,
          isAutoGenerated INTEGER DEFAULT 0,
          source TEXT,
          createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
          updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (property_id) REFERENCES properties(id),
          FOREIGN KEY (category_id) REFERENCES categories(id),
          FOREIGN KEY (counterparty_id) REFERENCES tenants(id)
        )
      `, (err) => { if (err) return reject(err); });

      // Create tenant_contracts table
      db.run(`
        CREATE TABLE IF NOT EXISTS tenant_contracts (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          tenant_id INTEGER NOT NULL,
          property_id INTEGER NOT NULL,
          startDate TEXT NOT NULL,
          endDate TEXT,
          coldRent REAL NOT NULL,
          sideCosts REAL NOT NULL DEFAULT 0,
          paymentDayOfMonth INTEGER NOT NULL DEFAULT 31,
          isActive INTEGER NOT NULL DEFAULT 1,
          notes TEXT,
          createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
          updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
          FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE
        )
      `, (err) => { if (err) return reject(err); });

      // Create rent_payments table
      db.run(`
        CREATE TABLE IF NOT EXISTS rent_payments (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          tenant_contract_id INTEGER NOT NULL,
          date TEXT NOT NULL,
          amount REAL NOT NULL,
          coldRentAmount REAL NOT NULL,
          sideCostsAmount REAL NOT NULL,
          status TEXT NOT NULL DEFAULT 'PENDING',
          paymentMethod TEXT,
          transaction_id INTEGER NOT NULL,
          source TEXT,
          notes TEXT,
          createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
          updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (tenant_contract_id) REFERENCES tenant_contracts(id) ON DELETE CASCADE,
          FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE
        )
      `, (err) => { if (err) return reject(err); });

      // Create recurring_payments table
      db.run(`
        CREATE TABLE IF NOT EXISTS recurring_payments (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          property_id INTEGER NOT NULL,
          amount REAL NOT NULL,
          frequency TEXT NOT NULL,
          startDate TEXT NOT NULL,
          endDate TEXT,
          nextPaymentDate TEXT,
          category_id INTEGER NOT NULL,
          description TEXT,
          counterparty_id INTEGER,
          isActive INTEGER NOT NULL DEFAULT 1,
          source TEXT,
          notes TEXT,
          createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
          updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
          FOREIGN KEY (category_id) REFERENCES categories(id),
          FOREIGN KEY (counterparty_id) REFERENCES tenants(id)
        )
      `, (err) => { if (err) return reject(err); });

      // Create idempotency_keys table
      db.run(`
        CREATE TABLE IF NOT EXISTS idempotency_keys (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          key TEXT NOT NULL UNIQUE,
          source TEXT,
          processed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
      `, (err) => { if (err) return reject(err); });

      // Create indexes
      db.run('CREATE INDEX IF NOT EXISTS idx_transactions_property ON transactions(property_id)', (err) => {});
      db.run('CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category_id)', (err) => {});
      db.run('CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date)', (err) => {});
      db.run('CREATE INDEX IF NOT EXISTS idx_rent_payments_contract ON rent_payments(tenant_contract_id)', (err) => {});
      db.run('CREATE INDEX IF NOT EXISTS idx_rent_payments_date ON rent_payments(date)', (err) => {});
      db.run('CREATE INDEX IF NOT EXISTS idx_idempotency_keys_key ON idempotency_keys(key)', (err) => {});

      resolve();
    });
  });
}

/**
 * Create test property
 * @param {object} data - Property data
 * @returns {Promise<object>} Created property with id
 */
async function createTestProperty(data) {
  const db = testDb || (await createTestDatabase());
  await initializeTestSchema();
  
  return new Promise((resolve, reject) => {
    const { name, address, type, purchasePrice, purchaseDate, rentAmount, size, 
            mortgage } = data;
    const m = mortgage || {};
    
    db.run(
      `INSERT INTO properties (name, address, type, purchasePrice, purchaseDate, rentAmount, size, 
        mortgage_loanAmount, mortgage_startDate, mortgage_interestRate, mortgage_principalRate, 
        mortgage_bankName, mortgage_paymentTiming, notes)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [name, address, type, purchasePrice, purchaseDate, rentAmount, size,
       m.loanAmount, m.startDate, m.interestRate, m.principalRate, m.bankName, m.paymentTiming, data.notes],
      function(err) {
        if (err) {
          return reject(err);
        }
        resolve({ id: this.lastID, ...data });
      }
    );
  });
}

/**
 * Create test tenant
 * @param {object} data - Tenant data
 * @returns {Promise<object>} Created tenant with id
 */
async function createTestTenant(data) {
  const db = testDb || (await createTestDatabase());
  await initializeTestSchema();
  
  return new Promise((resolve, reject) => {
    db.run(
      'INSERT INTO tenants (name, email, phone, address, notes) VALUES (?, ?, ?, ?, ?)',
      [data.name, data.email, data.phone, data.address, data.notes],
      function(err) {
        if (err) {
          return reject(err);
        }
        resolve({ id: this.lastID, ...data });
      }
    );
  });
}

/**
 * Create test category
 * @param {object} data - Category data
 * @returns {Promise<object>} Created category with id
 */
async function createTestCategory(data) {
  const db = testDb || (await createTestDatabase());
  await initializeTestSchema();
  
  return new Promise((resolve, reject) => {
    db.run(
      'INSERT INTO categories (name, type, isTaxRelevant) VALUES (?, ?, ?)',
      [data.name, data.type || 'EXPENSE', data.isTaxRelevant || 0],
      function(err) {
        if (err) {
          return reject(err);
        }
        resolve({ id: this.lastID, ...data });
      }
    );
  });
}

/**
 * Create test tenant contract
 * @param {object} data - Contract data
 * @returns {Promise<object>} Created contract with id
 */
async function createTestTenantContract(data) {
  const db = testDb || (await createTestDatabase());
  await initializeTestSchema();
  
  return new Promise((resolve, reject) => {
    db.run(
      `INSERT INTO tenant_contracts (tenant_id, property_id, startDate, endDate, 
        coldRent, sideCosts, paymentDayOfMonth, isActive, notes)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [data.tenantId, data.propertyId, data.startDate, data.endDate,
       data.coldRent, data.sideCosts || 0, data.paymentDayOfMonth || 31, data.isActive || 1, data.notes],
      function(err) {
        if (err) {
          return reject(err);
        }
        resolve({ id: this.lastID, ...data });
      }
    );
  });
}

/**
 * Create test recurring payment
 * @param {object} data - Recurring payment data
 * @returns {Promise<object>} Created recurring payment with id
 */
async function createTestRecurringPayment(data) {
  const db = testDb || (await createTestDatabase());
  await initializeTestSchema();
  
  return new Promise((resolve, reject) => {
    db.run(
      `INSERT INTO recurring_payments (property_id, amount, frequency, startDate, endDate, 
        nextPaymentDate, category_id, description, counterparty_id, isActive, notes)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [data.propertyId, data.amount, data.frequency, data.startDate, data.endDate,
       data.nextPaymentDate, data.categoryId, data.description, data.counterpartyId || null,
       data.isActive || 1, data.notes],
      function(err) {
        if (err) {
          return reject(err);
        }
        resolve({ id: this.lastID, ...data });
      }
    );
  });
}

/**
 * Get all records from a table
 * @param {string} tableName - Table name
 * @returns {Promise<Array>} Array of records
 */
async function getAllRecords(tableName) {
  const db = testDb || (await createTestDatabase());
  
  return new Promise((resolve, reject) => {
    db.all(`SELECT * FROM ${tableName}`, [], (err, rows) => {
      if (err) {
        return reject(err);
      }
      resolve(rows);
    });
  });
}

/**
 * Clear all data from a table
 * @param {string} tableName - Table name
 * @returns {Promise<void>}
 */
async function clearTable(tableName) {
  const db = testDb || (await createTestDatabase());
  
  return new Promise((resolve, reject) => {
    db.run(`DELETE FROM ${tableName}`, (err) => {
      if (err) {
        return reject(err);
      }
      resolve();
    });
  });
}

/**
 * Clear all test data
 * @returns {Promise<void>}
 */
async function clearAllTestData() {
  const tables = [
    'transactions',
    'rent_payments',
    'recurring_payments',
    'tenant_contracts',
    'tenants',
    'properties',
    'categories',
    'idempotency_keys'
  ];
  
  for (const table of tables) {
    await clearTable(table);
  }
}

/**
 * Close test database connection
 * @returns {Promise<void>}
 */
async function closeTestDatabase() {
  return new Promise((resolve) => {
    if (testDb) {
      testDb.close();
      testDb = null;
    }
    resolve();
  });
}

/**
 * Clean up test database file
 * @returns {Promise<void>}
 */
async function cleanupTestDatabase() {
  await closeTestDatabase();
  
  if (fs.existsSync(TEST_DB_PATH)) {
    fs.unlinkSync(TEST_DB_PATH);
  }
}

module.exports = {
  createTestDatabase,
  initializeTestSchema,
  createTestProperty,
  createTestTenant,
  createTestCategory,
  createTestTenantContract,
  createTestRecurringPayment,
  getAllRecords,
  clearTable,
  clearAllTestData,
  closeTestDatabase,
  cleanupTestDatabase,
  TEST_DB_PATH
};
